### ISSUE TITLE
Funding for Readme file updation

### ISSUE THREAD

**Issue by Santhosh1692** [ethereum-cat-herders/funding#440]
CL https://github.com/ethereum/pm/pull/674 

ACD https://github.com/ethereum/pm/pull/673

For CL, it was necessary to re-update the entire readme file for all 97 meetings. As there was a consistency issue with the title, I had to manually check and update it, which took about an hour and 15 minutes. Let me know how much I can raise fund request for @poojaranjan

**Comment by poojaranjan** [comment]
@Santhosh1692  
I'm afraid, we don't have any allocated bounty for README updating as this is considered to be a part of notes submission.

You were selected for updating README because, ~40 % of the notes (ACD & CL) were documented by you. At the time, you were assigned for ACD 146 & CL 95 which were 18 mins and 44 mins respectively. Meeting were way shorter than 90 mins. However, full bounty of 150 USD each were paid.  Our hope with selection was to optimize effort by utilizing it for making README up to date.

**Comment by Santhosh1692** [comment]
Got it. Makes sense. I am closing this PR
